# -*- coding: utf-8 -*-
"""kalkulator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/SecretDiscorder/PyShic/blob/main/kalkulator.ipynb
"""
from decimal import Decimal, getcontext
import math
def faktorial(n):
    if n == 0 or n == 1:
        return 1
    else:
        return n * faktorial(n - 1)
    
def faktor():
    num = int(input("Masukkan bilangan untuk menghitung faktorial: "))
    if num < 0:
        print("Faktorial tidak dapat dihitung untuk bilangan negatif.")
    elif num == 0:
        print("Faktorial dari 0 adalah 1.")
    else:
        hasil_faktorial = faktorial(num)
        print(f"Faktorial dari {num} adalah {hasil_faktorial}.")

    
def penjumlahan():
  a= (float(input("Masukan nilai pertama: ")));
  b= (float(input("Masukan nilai kedua: ")));
  c= a+b;
  print(c);

def pengurangan():
  a= (float(input("Masukan nilai pertama: ")));
  b= (float(input("Masukan nilai kedua: ")));
  c= a-b;
  print(c);
def spldv():
  a= (float(input("Masukan nilai x1: ")));
  b= (float(input("Masukan nilai y1: ")));
  hasil1= (float(input("hasil x1+y1= ")));
  c= (float(input("Masukan nilai x2: ")));
  d= (float(input("Masukan nilai y2: ")));
  hasil2= (float(input("hasil x2+y2= ")));
  determinan= (a*d)-(b*c);
  determinan_x= (d*hasil1)-(b*hasil2);
  determinan_y= (a*hasil2)-(c*hasil1);
  x= determinan_x/determinan;
  y= determinan_y/determinan;
  print("determinan: ", determinan);

  print("determinan_x: ", determinan_x);

  print("determinan_y: ", determinan_y);


  print("x: ", x);
  print("y: ", y);


def pembagian():
  a= (float(input("Masukan nilai pertama: ")));
  b= (float(input("Masukan nilai kedua: ")));
  c= a/b;
  print(c);

def perkalian():
  a= (float(input("Masukan nilai pertama: ")));
  b= (float(input("Masukan nilai kedua: ")));
  c= a*b;
  print(c);

def pangkat():
  getcontext().prec = 10000
  a= (int(input("masukan bilangan: ")));
  b= (int(input("masukan pangkat: ")));
  c= Decimal(a)**b;
  digit_satuan= c % 10
  print("{:.0f}".format(c));
  print("angka satuan: ", digit_satuan)

def kuadrat():
  a= (float(input("masukan bilangan: ")));

  c= math.sqrt(a);
  print(c);

def logaritma():
  a= (float(input("masukan bilangan a (untuk a log b): ")));
  b= (float(input("masukan Bilangan b (untuk a log b): ")));

  c= math.log(b, a);

  print(c);
def sincostan():
  a= (int(input("masukan bilangan sin(derajat):  ")));
  d1= math.radians(a);
  c1= math.sin(d1);

  d2= math.radians(a);
  c2= math.cos(d2);

  d3= math.radians(a);
  c3= math.tan(d3);

  print("jadi sin= ",(c1));
  print("jadi cos= ",(c2));
  print("jadi tan= ",(c3));
def degree():
  b= (float(input("masukan bilangan(hasil berupa derajat) : ")));
  c= math.asin(b); #radian
  d= math.degrees(c); #derajat
  c2= math.acos(b); #radian
  d2= math.degrees(c2); #derajat
  print("derajat sin",(d))
  print("derajat cos",(d2))
  return 0;
  
def pw():
  nama= input("masukan nama: ")
  password= input("masukan pass: ")
  if nama=='bima' and password=='crackzy':
    main()
  else:
    print("nama dan password salah")
  
def main():
  print("program kalkulator");
  print("1. penjumlahan");
  print("2. pengurangan");
  print("3. perkalian");
  print("4. pembagian");
  print("5. pangkat");
  print("6. kuadrat");
  print("7. logaritma");
  print("8. sincostan");
  print("9. Sin to degree");
  print("10. SPLDV");
  print("11. faktorial");
  pilihan = (int(input("masukan pilihan anda: ")))
  if pilihan == 1:
    penjumlahan();
  elif pilihan == 2:
    pengurangan();
  elif pilihan == 3:
    perkalian();
  elif pilihan == 4:
    pembagian();
  elif pilihan == 5:
    pangkat();
  elif pilihan == 6:
    kuadrat();
  elif pilihan == 7:
    logaritma();
  elif pilihan == 8:
    sincostan();
  elif pilihan == 9:
    degree();
  elif pilihan == 10:
    spldv();
  elif pilihan == 11:
    faktor();
  else :
    while True:
      main();
  return pilihan;

if __name__ == "__main__":
  while True:
    pw()